on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  FLUTTER_VERSION: '3.24.1'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Set up environment vars
        shell: bash
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        shell: bash
        run: |
          choco install sed make yq -y
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Release On Windows
        run: |
          flutter pub get
          flutter config --enable-windows-desktop
          dart pub global activate flutter_distributor
          flutter_distributor release --name onwindows
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y appstream clang cmake desktop-file-utils fakeroot fuse gir1.2-appindicator3-0.1 libappindicator3-1 libappindicator3-dev libarchive-tools libgdk-pixbuf2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libjsoncpp25 libjsoncpp-dev libmpv-dev libnotify-bin libnotify-dev libsecret-1-0 libsecret-1-dev libunwind-dev locate make mpv ninja-build patchelf pkg-config python3-pip python3-setuptools strace tar xmlstarlet 

      - name: Install AppImage Tool
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv -v appimagetool /usr/local/bin/

      - name: Set up environment vars
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          curl -sS https://webi.sh/yq | sh
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Release On Linux
        run: |
          flutter pub get
          dart pub global activate flutter_distributor
          flutter_distributor release --name onlinux
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Dependencies
        run: |
          python3 -m pip install --break-system-packages setuptools
          npm install --break-system-packages -g appdmg      

      - name: Set version environment vars
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})
          echo "SEMANTIC_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "FLUTTER_VERSION=${TAG_NAME}+${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          brew install yq
          yq -i ".version |= \"${SEMANTIC_VERSION}+\"" pubspec.yaml
          yq -i '.version += strenv(GITHUB_RUN_NUMBER)' pubspec.yaml

      - name: Release On Mac OS X
        run: |
          flutter pub get
          flutter config --enable-macos-desktop
          dart pub global activate flutter_distributor
          flutter_distributor release --name onmac
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release:
    runs-on: ubuntu-latest
    needs:
      - windows
      - linux
      - macos
    steps:
      - uses: actions/checkout@v4
      - name: No longer draft
        run: |
          gh release edit "$(echo ${GITHUB_REF#refs/tags/})" --draft=false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
