on:
  push:
    tags:
      - v*

permissions:
#  actions: read|write|none
#  checks: read|write|none
  contents: write
#  deployments: read|write|none
#  id-token: read|write|none
#  issues: read|write|none
#  discussions: read|write|none
#  packages: read|write|none
#  pages: read|write|none
#  pull-requests: read|write|none
#  repository-projects: read|write|none
#  security-events: read|write|none
#  statuses: read|write|none

env:
  FLUTTER_VERSION: '3.13.9'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Build Windows Executable
        run: |
          flutter upgrade
          flutter pub get
          flutter config --enable-windows-desktop
          dart pub global activate flutter_distributor
          make innoinstall
          flutter_distributor package --platform=windows --targets=exe --skip-clean
          mv dist/**/lemmy_notify-*-windows-setup.exe dist/lemmy_notify-windows-x86_64-setup.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: dist/
          retention-days: 1

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tar clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse libunwind-dev locate patchelf gir1.2-appindicator3-0.1 libappindicator3-1 libappindicator3-dev libsecret-1-0 libjsoncpp25 libsecret-1-dev libjsoncpp-dev libnotify-bin libnotify-dev mpv libmpv-dev libsecret-1-dev libjsoncpp-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install AppImage Tool
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv appimagetool /usr/local/bin/

      - name: Build Linux Packages
        run: |
          flutter upgrade
          flutter pub get
          dart pub global activate flutter_distributor
          alias dpkg-deb="dpkg-deb --Zxz"
          flutter_distributor package --platform=linux --targets=deb
          flutter_distributor package --platform=linux --targets=appimage
          flutter_distributor package --platform=linux --targets=rpm

      - name: Move Files to dist
        run: |
          mv dist/**/lemmy_notify-*-linux.deb dist/lemmy_notify-linux-x86_64.deb
          mv dist/**/lemmy_notify-*-linux.rpm dist/lemmy_notify-linux-x86_64.rpm
          mv dist/**/lemmy_notify-*-linux.AppImage dist/lemmy_notify-linux-x86_64.AppImage

      - uses: actions/upload-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: dist/
          retention-days: 1

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse xmlstarlet libsecret-1-dev libjsoncpp-dev

      - name: Build Apk
        run: |
          flutter upgrade
          flutter pub get
          flutter build apk
          flutter build appbundle
          mv build/app/outputs/apk/release/app-release.apk build/lemmy_notify-android-all-arch.apk
          mv build/app/outputs/bundle/release/app-release.aab build/lemmy_notify-playstore-all-arch.aab

      - uses: actions/upload-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: |
            build/lemmy_notify-android-all-arch.apk
            build/lemmy_notify-playstore-all-arch.aab
          retention-days: 1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION  }}

      - name: Build Macos App
        run: |
          flutter upgrade
          flutter pub get
          flutter config --enable-macos-desktop
          flutter build macos
          du -sh build/macos/Build/Products/Release/*

      - name: Package Macos App
        run: |
          python3 -m pip install setuptools
          npm install -g appdmg
          mkdir -p build/${{ env.BUILD_VERSION }}
          appdmg appdmg.json build/lemmy_notify-macos-universal.dmg

      - uses: actions/upload-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: |
            build/lemmy_notify-macos-universal.dmg
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs:
      - windows
      - linux
      - android
      - macos
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: ./lemmy_notify-Release-Binaries

      - name: Install dependencies
        run: sudo apt-get install tree -y

      - name: Generate Checksums
        run: |
          tree .
          md5sum lemmy_notify-Release-Binaries/* >> RELEASE.md5sum
          sha256sum lemmy_notify-Release-Binaries/* >> RELEASE.sha256sum
          sed -i 's|lemmy_notify-Release-Binaries/||' RELEASE.sha256sum RELEASE.md5sum

      - uses: actions/upload-artifact@v3
        with:
          name: lemmy_notify-Release-Binaries
          path: |
            RELEASE.md5sum
            RELEASE.sha256sum
          retention-days: 1

      - name: Upload Release Binaries (stable)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: lemmy_notify-Release-Binaries/*,RELEASE.sha256sum,RELEASE.md5sum
